version: '3.8'

services:
  app1:
    image: tic-tac-toe:latest
    container_name: app1
    depends_on:
      - redis
    ports:
      - "8081:8080"
    environment:
      - PLAYER_ID=ivan
      - PLAYER_FIXED_RATE=5000
      - OPPONENT_PLAYER_URL=http://app2:8080
      - SPRING_DATA_REDIS_HOST=redis

  app2:
    image: tic-tac-toe:latest
    container_name: app2
    depends_on:
      - redis
    ports:
      - "8082:8080"
    environment:
      - PLAYER_ID=sergey
      - PLAYER_FIXED_RATE=7000
      - OPPONENT_PLAYER_URL=http://app1:8080
      - SPRING_DATA_REDIS_HOST=redis

  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    restart: unless-stopped
